on:
  push

jobs:
  build-it-image:
    env:
      PULL_REQUEST_USER: ${{ github.actor }}
    name: build-it-image
    runs-on: [self-hosted, "${{ github.actor }}"]
    timeout-minutes: 20
    steps:
      - name: Test Echo
        run: echo "current user is " $PULL_REQUEST_USER


