on:
  push

jobs:
  build-it-image:
    name: build-it-image
    runs-on: ubuntu-latest,${{ author }}
    timeout-minutes: 20
    steps:
      - name: Test Echo
        run: echo "current user is ${author}"
 