on:
  push

jobs:
  build-it-image:
    
    name: build-it-image
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      env:
        PULL_REQUEST_USER: ${{ github.event.pull_request.user.login }}
      - name: Test Echo
        run: echo "current user is " ${env.PULL_REQUEST_USER}


